
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[249] =
    {   0,
        0,    0,   66,   65,   63,    8,   65,   59,    5,   15,
       18,   19,    3,    1,   24,    2,   59,    4,   61,   61,
       25,    9,   26,   10,   60,   60,   20,   65,   21,   17,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   22,   16,   23,   14,    0,
       62,    0,    0,    6,    0,   64,   61,   11,   13,   12,
       60,    0,    0,    0,    0,   60,   60,   60,   60,   60,
       60,   51,   60,   60,   60,   60,   60,   60,   30,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
        7,    0,    0,    0,    0,    0,    0,    0,    0,   64,

        0,    0,    0,    0,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   33,   60,   28,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,    0,    0,    0,    0,    0,    0,    0,   64,
        0,    0,    0,    0,   37,   60,   42,   27,   60,   60,
       60,   60,   31,   52,   60,   60,   55,   45,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   29,
       60,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       35,   43,   60,   60,   60,   60,   39,   60,   60,   47,
       60,   60,   60,   60,   60,   60,   54,   60,   32,    0,

        0,    0,    0,    0,    0,   60,   60,   60,   40,   38,
       60,   36,   48,   56,   49,   53,   41,   60,   60,    0,
        0,    0,    0,    0,   60,   44,   60,   57,   60,    0,
        0,    0,    0,   34,   46,   50,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,    1,   23,   24,
       25,   26,   11,    1,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   28,   28,   30,   28,   28,   31,   28,   28,
       32,   33,   34,   35,   28,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   45,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    5,    1,    1,    1,    1,    5,    6,    6,    7,
        7,    1,    7,    1,    1,    8,    8,    9,    9,    9,
        8,   10,   10,   10,   10,   10,   10,   10,   11,   10,
       10,   11,   10,   11,   11,   11,   10,   11,   10,   10,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[290] =
    {   0,
        0,    0,  559,  644,  644,  533,   57,  509,  644,  542,
      644,  644,  644,  644,  644,  644,  644,   51,  644,   46,
      644,  522,  521,  516,  507,   62,  644,   41,  644,  644,
       39,   40,   41,   43,   52,   53,   47,   65,   54,   42,
       69,   46,   75,   78,   45,  644,  473,  644,  644,   74,
      644,   99,  485,  644,  113,    0,  111,  644,  644,  644,
      496,   79,   82,    0,    0,   85,  102,   88,   89,  103,
      104,  105,  110,  107,  111,  114,  115,  116,  495,  117,
      120,  126,  122,  133,  125,  140,  123,  143,  145,  146,
      644,  174,    0,    0,    0,  485,  188,  194,  196,    0,

        0,    0,    0,    0,  153,  149,  171,  168,  172,  173,
      179,  181,  180,  184,  186,  489,  185,  484,  190,  194,
      196,  197,  198,  200,  201,  203,  206,  204,  209,  208,
      215,  210,  243,    0,  270,    0,  469,  242,  258,  644,
        0,    0,    0,    0,  478,  220,  477,  472,  232,  234,
      238,  235,  471,  466,  236,  240,  465,  460,  242,  237,
      246,  241,  251,  252,  113,  150,  265,  250,  272,  459,
      247,  295,    0,  322,    0,  432,    0,    0,    0,    0,
      453,  448,  282,  279,  280,  283,  447,  284,  285,  442,
      286,  289,  302,  291,  290,  306,  441,  288,  436,    0,

        0,  429,    0,    0,    0,  419,  314,  294,  418,  413,
      317,  412,  407,  406,  401,  400,  395,  323,  332,    0,
      334,  387,    0,    0,  333,  382,  318,  368,  335,    0,
      395,    0,    0,  364,  363,  338,    0,  330,    0,    0,
        0,    0,    0,  335,  309,  310,  644,  644,  374,  382,
      391,  402,  413,  421,  427,  433,  439,  445,  454,  462,
      468,  474,  480,  486,  492,  498,  504,  510,  516,  522,
      528,  534,  540,  546,  552,  558,  564,  570,  576,  582,
      588,  594,  600,  606,  612,  618,  624,  630,  632
    } ;

static yyconst flex_int16_t yy_def[290] =
    {   0,
      248,    1,  248,  248,  248,  248,  249,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  250,  250,  248,  248,  248,  248,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  248,  248,  248,  248,  249,
      248,  251,  248,  248,  252,  253,  248,  248,  248,  248,
      250,  248,  249,  254,  255,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      248,  249,  256,  257,  258,  248,  252,  252,  259,  253,

      260,  261,  262,  263,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  249,  264,  249,  265,  248,  252,  252,  248,
      266,  267,  268,  269,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  249,  270,  249,  271,  248,  272,  273,  274,  275,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  276,

      277,  248,  278,  279,  280,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  281,
      249,  248,  282,  283,  250,  250,  250,  250,  250,  284,
      248,  285,  286,  250,  250,  250,  287,  248,  288,  275,
      277,  289,  279,  289,  248,  248,  248,    0,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248
    } ;

static yyconst flex_int16_t yy_nxt[708] =
    {   0,
        4,    5,    5,    4,    5,    6,    7,    8,    9,   10,
        4,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   21,   22,   23,   24,   25,   25,   26,   25,
       25,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   25,   38,   25,   25,   39,   25,   25,   25,
       25,   40,   41,   42,   43,   44,   45,   25,   25,   25,
       46,   47,   48,   51,   55,   57,   57,   57,   63,   56,
       64,   62,   62,   62,   62,   62,   68,   62,   62,   62,
       51,   82,   71,   69,   62,   62,   62,   90,   51,   52,
       70,   67,   72,   66,   62,   65,   78,   62,   73,   76,

       74,   62,   77,   81,   87,   79,   52,   62,  101,   75,
       62,   83,   84,   80,   52,   98,   98,   62,   92,   92,
       62,   62,   85,   88,  108,   86,   99,   89,   93,   94,
       57,   57,   57,  102,   62,   62,   62,   62,  105,   62,
      107,  106,   62,   62,  110,   62,   62,   62,   62,   62,
      194,  109,   62,   95,   62,   62,   94,   62,   62,  111,
      125,  113,  112,  115,  114,   62,  116,  120,  119,  117,
      118,  122,   62,  128,  123,   62,  126,   62,   62,  121,
       51,   62,   62,  127,  146,   62,  129,  195,  131,  132,
       98,   98,  124,  133,  133,  130,   98,   98,  139,  139,

       62,   99,  145,   62,   62,   62,   52,   99,  151,   99,
      147,   62,   62,   62,  140,  152,   62,   62,   62,  148,
      153,  156,   62,  155,  149,  150,   62,  154,   62,   62,
       62,  158,   62,   62,  157,   62,   62,  159,   62,  163,
       62,   62,   62,  167,   98,   98,  162,   62,  161,   51,
      160,  169,   62,  170,  164,   99,  171,  165,  168,  166,
       98,   98,  172,  172,   62,  181,   62,   62,   62,   62,
       62,   99,   62,   62,   62,   52,   51,  183,   62,   62,
      191,  185,   62,   62,   62,  182,  199,  186,  189,  174,
      174,  174,  184,  187,  188,  193,  174,   62,  197,  190,

      192,   51,   52,  196,   62,  174,  174,  174,  174,  174,
      174,   62,   62,  198,   62,   62,   62,   62,   62,  209,
       62,   62,   62,   62,  213,  208,   62,   52,   51,  214,
      207,  210,  217,  212,   62,  247,  219,  211,   62,  215,
       51,  174,  174,  174,  216,  218,   62,  226,  174,   62,
       62,  246,  245,  242,   52,   62,  227,  174,  174,  174,
      174,  174,  174,  228,   62,   62,   52,   62,  225,  235,
       62,  229,  234,  236,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   61,   61,   61,   61,   61,
       61,   61,   61,   50,   50,   62,   62,   50,   50,  238,

       62,   50,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,  100,   62,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  103,  103,  231,   62,  103,  103,
      104,  104,   62,   62,  104,  104,  134,  134,   62,   62,
      134,  134,  135,  135,   62,   62,  135,  135,  136,  136,
       62,   62,  136,  136,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  141,  141,  222,   62,  141,
      141,  142,  142,   62,   62,  142,  142,  143,  143,   62,
       62,  143,  143,  144,  144,   62,  202,  144,  144,  173,
      173,   62,   62,  173,  173,  175,  175,   62,   62,  175,

      175,  177,  177,   62,   62,  177,  177,  178,  178,   62,
       62,  178,  178,  179,  179,  176,   62,  179,  179,  180,
      180,   62,  137,  180,  180,  200,  200,   62,   62,  200,
      200,  201,  201,   96,   91,  201,  201,  203,  203,   62,
       60,  203,  203,  204,  204,   59,   58,  204,  204,  205,
      205,   54,   53,  205,  205,  206,  206,   49,  248,  206,
      206,  220,  220,  248,  248,  220,  220,  221,  221,  248,
      248,  221,  221,  223,  223,  248,  248,  223,  223,   61,
       61,  248,  248,   61,   61,  224,  224,  248,  248,  224,
      224,  230,  230,  248,  248,  230,  230,  232,  232,  248,

      248,  232,  232,  233,  233,  248,  248,  233,  233,  237,
      237,  248,  248,  237,  237,  239,  239,  248,  248,  239,
      239,  240,  240,  248,  248,  240,  240,  241,  241,  248,
      248,  241,  241,  243,  243,  248,  248,  243,  243,  244,
      244,  244,  244,    3,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248
    } ;

static yyconst flex_int16_t yy_chk[708] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,   18,   20,   20,   20,   26,   18,
       28,   31,   32,   33,   40,   34,   33,   45,   42,   37,
       50,   40,   34,   33,   35,   36,   39,   45,   63,    7,
       33,   32,   34,   31,   26,   28,   37,   38,   35,   36,

       35,   41,   36,   39,   42,   38,   50,   43,   62,   35,
       44,   41,   41,   38,   63,   55,   55,   66,   52,   52,
       68,   69,   41,   43,   69,   41,   55,   44,   52,   52,
       57,   57,   57,   62,   67,   70,   71,   72,   66,   74,
       68,   67,   73,   75,   71,  165,   76,   77,   78,   80,
      165,   70,   81,   52,   83,   87,   52,   85,   82,   72,
       85,   74,   73,   76,   75,   84,   77,   82,   81,   78,
       80,   83,   86,   87,   84,   88,   85,   89,   90,   82,
       92,  106,  166,   86,  106,  105,   88,  166,   89,   90,
       97,   97,   84,   92,   92,   88,   98,   98,   99,   99,

      108,   97,  105,  107,  109,  110,   92,   98,  110,   99,
      107,  111,  113,  112,   99,  111,  114,  117,  115,  108,
      112,  115,  119,  114,  109,  109,  120,  113,  121,  122,
      123,  119,  124,  125,  117,  126,  128,  120,  127,  124,
      130,  129,  132,  128,  138,  138,  123,  131,  122,  133,
      121,  130,  146,  131,  125,  138,  132,  126,  129,  127,
      139,  139,  133,  133,  149,  146,  150,  152,  155,  160,
      151,  139,  156,  162,  159,  133,  135,  150,  161,  171,
      162,  152,  168,  163,  164,  149,  171,  155,  160,  135,
      135,  135,  151,  156,  159,  164,  135,  167,  168,  161,

      163,  172,  135,  167,  169,  135,  135,  135,  135,  135,
      135,  184,  185,  169,  183,  186,  188,  189,  191,  185,
      198,  192,  195,  194,  191,  184,  208,  172,  174,  192,
      183,  186,  195,  189,  193,  246,  198,  188,  196,  193,
      221,  174,  174,  174,  194,  196,  207,  208,  174,  211,
      227,  245,  244,  238,  174,  218,  211,  174,  174,  174,
      174,  174,  174,  218,  219,  225,  221,  229,  207,  227,
      236,  219,  225,  229,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  250,  250,  250,  250,  250,
      250,  250,  250,  251,  251,  235,  234,  251,  251,  231,

      228,  251,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  253,  226,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  254,  254,  222,  217,  254,  254,
      255,  255,  216,  215,  255,  255,  256,  256,  214,  213,
      256,  256,  257,  257,  212,  210,  257,  257,  258,  258,
      209,  206,  258,  258,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  260,  260,  202,  199,  260,
      260,  261,  261,  197,  190,  261,  261,  262,  262,  187,
      182,  262,  262,  263,  263,  181,  176,  263,  263,  264,
      264,  170,  158,  264,  264,  265,  265,  157,  154,  265,

      265,  266,  266,  153,  148,  266,  266,  267,  267,  147,
      145,  267,  267,  268,  268,  137,  118,  268,  268,  269,
      269,  116,   96,  269,  269,  270,  270,   79,   61,  270,
      270,  271,  271,   53,   47,  271,  271,  272,  272,   25,
       24,  272,  272,  273,  273,   23,   22,  273,  273,  274,
      274,   10,    8,  274,  274,  275,  275,    6,    3,  275,
      275,  276,  276,    0,    0,  276,  276,  277,  277,    0,
        0,  277,  277,  278,  278,    0,    0,  278,  278,  279,
      279,    0,    0,  279,  279,  280,  280,    0,    0,  280,
      280,  281,  281,    0,    0,  281,  281,  282,  282,    0,

        0,  282,  282,  283,  283,    0,    0,  283,  283,  284,
      284,    0,    0,  284,  284,  285,  285,    0,    0,  285,
      285,  286,  286,    0,    0,  286,  286,  287,  287,    0,
        0,  287,  287,  288,  288,    0,    0,  288,  288,  289,
      289,  289,  289,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "includes/scanner/scanner.l"
/* 
============================================================================
* Program Name 	: scanner.l
* Author		: #B96902133, Hakki Caner Kirmizi
* Description		: A C source code scanner written with flex.
* Environment		: Windows-7 Entreprise
* Editor		: vim 7.2 for WIN 
* Integration Tests	: linux2.csie.ntu.edu.tw
* Flex			: 2.5.35
* Compiler		: gcc (Debian 4.4.3-3) 4.4.3
* Version Control	: TortoiseSVN 1.6.7, Build 18415 - 32 Bit
* Project Hosting	: http://code.google.com/p/c-source-scanner/
* 
* INSTRUCTIONS
* ------------
* Build		: flex scanner.l
* Compile		: gcc lex.yy.c
* Run			: There are two options...
*  1) a.out [input-filename] // recommended for long source codes
*  2) a.out // hit enter and use stdin; BE AWARE OF BUFFER SIZE!!!
* 
* DETAILS
* -------
* c-source-scanner is written for these purposes:
* 1) To understand how to scan a program's source code file.
* 2) To understand how to use a scanner generator to 'generate' a
* source code generator.
* 3) To understand how to use finite automata concept via defining regular
* expressions to match the lexeme of the code and output the tokens.
*
* c-source-scanner is NOT written for these purposes (at-least-for-now):
* 1) To provide a 'full' scanner program for C language.
* 2) To construct a symbol table for future enhancements of building a
* real compiler.
*
* NOTES
* -----
* 1) scanner.l follows up the c naming conventions:
* http://www.cprogramming.com/tutorial/style_naming_conventions.html
* 2) Constant ID of the ASCII characters are same with their ASCII codes.
* 3) Regex for comments based on:
* http://ostermiller.org/findcomment.html
* 4) O'Reilly's Flex&Bison book is a very good resource, if you want to
* know more about flex and bison.
============================================================================
*/
/* we do not need flex library */
/* ----- DEFINITIONS PART ----- */
/* ============================ */
/* DEFINITIONS FOR TOKEN CODES */
/* --------------------------- */
/* ' The literal block %{ ... %} ' in this part is copied to verbatim to the generated
C source file near the beginning, before the beginning of yylex() */
#line 60 "includes/scanner/scanner.l"
#include "queue_ops.h"
#define PLUS "+"
#define MINUS "-"
#define MULT "*"
#define DIV "/"
#define PERCENT "%"
#define LAND "&&"
#define LOR "||"
#define LNOT "!"
#define LESSTHAN "<"
#define GREATERTHAN ">"
#define LTEQUAL ">="
#define GTEQUAL "<="
#define EQUAL "=="
#define NOTEQUAL "!="
#define BITAND "&"
#define BITOR "|" 
#define BITXOR "^"
#define LPARA "("
#define RPARA ")"
#define LBRACKET "["
#define RBRACKET "]"
#define LCURLY "{"
#define RCURLY "}"
#define COMMA ","
#define SEMICOLON ";"
#define ASSIGN "="
#define CHARSYM "char"
#define INTSYM "int"
#define VOIDSYM "void"
#define AUTOSYM "auto"
#define EXTERNSYM "extern"	
#define FLOATSYM "float"
#define DOUBLESYM "double"
#define SWITCHSYM "switch"
#define CASESYM "case"
#define CONSTSYM "const"
#define DEFAULTSYM "default"
#define LONGSYM "long"			
#define REGISTERSYM "register"
#define SHORTSYM "short"		
#define SIGNEDSYM "signed"
#define STATICSYM "static"
#define UNSIGNEDSYM "unsigned"
#define IFSYM "if"
#define ELSESYM "else"
#define WHILESYM "while"
#define DOSYM "do"
#define FORSYM "for"
#define CONTINUESYM "continue"
#define BREAKSYM "break"
#define RETURNSYM "return"
#define ENUMSYM "enum"		
#define STRUCTSYM "struct"
#define UNIONSYM "union"	
#define GOTOSYM "goto"
#define SIZEOFSYM "sizeof"
#define TYPEDEFSYM "typedef"
#define IDENTIFIER 258
#define INTEGER 259
#define STRING 260
#define DELIMITER 261
#define COMMENT 262

queue_ops queue_obj;
int queue_ops::count= 0;

/* DEFINITIONS FOR FINITE AUTOMATA */
/* ------------------------------- */
/* Universal Character Name: the naming conventions for UCS defined by International Standard ISO/IEC 10646 */
/* DIGIT: any number from 0 to 9 */
/* LETTER: any uppercase or lowercase letter */
/* DELIMITER: any occurence of 'space', 'tab' or 'newline' */
/* IDENTIFIER: starting with a letter; following by any occurence of letter, digit or underscore */
/* INTEGER: 0 or more occurence of consecutive digits */
/* STRING: anything between double quote; just considers \" and \\ characters */
/* COMMENT: any c style comment */
#line 830 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 160 "includes/scanner/scanner.l"

 /* ----- RULES PART ----- */
 /* ====================== */

 /* RULES FOR OPERATORS AND PUNCTUATIONS */
 /* ------------------------------------ */
#line 1019 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 249 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 644 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 166 "includes/scanner/scanner.l"
{ // printf("%s\n", PLUS); 
      queue_obj.push_into_queue(PLUS, 1); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 168 "includes/scanner/scanner.l"
{ // printf("%s\n", MINUS); 
      queue_obj.push_into_queue(MINUS, 1); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 170 "includes/scanner/scanner.l"
{ // printf("%s\n", MULT);
      queue_obj.push_into_queue(MULT, 1); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 172 "includes/scanner/scanner.l"
{ // printf("%s\n", DIV);
      queue_obj.push_into_queue(DIV, 1); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 174 "includes/scanner/scanner.l"
{ // printf("%s\n", PERCENT);
      queue_obj.push_into_queue(PERCENT, 1); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 176 "includes/scanner/scanner.l"
{ // printf("%s\n", LAND);
      queue_obj.push_into_queue(LAND, 1); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 178 "includes/scanner/scanner.l"
{ // printf("%s\n", LOR); 
      queue_obj.push_into_queue(LOR, 1); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 180 "includes/scanner/scanner.l"
{ // printf("%s\n", LNOT); 
      queue_obj.push_into_queue(LNOT, 1); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 182 "includes/scanner/scanner.l"
{ // printf("%s\n", LESSTHAN); 
      queue_obj.push_into_queue(LESSTHAN, 1);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 184 "includes/scanner/scanner.l"
{ // printf("%s\n", GREATERTHAN); 
      queue_obj.push_into_queue(GREATERTHAN, 1); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 186 "includes/scanner/scanner.l"
{ // printf("%s\n", LTEQUAL); 
      queue_obj.push_into_queue(LTEQUAL, 1); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 188 "includes/scanner/scanner.l"
{ // printf("%s\n", GTEQUAL); 
      queue_obj.push_into_queue(GTEQUAL, 1); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 190 "includes/scanner/scanner.l"
{ // printf("%s\n", EQUAL);
      queue_obj.push_into_queue(EQUAL, 1); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 192 "includes/scanner/scanner.l"
{ // printf("%s\n", NOTEQUAL);
      queue_obj.push_into_queue(NOTEQUAL, 1); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 194 "includes/scanner/scanner.l"
{ // printf("%s\n", BITAND);
      queue_obj.push_into_queue(BITAND, 1); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 196 "includes/scanner/scanner.l"
{ // printf("%s\n", BITOR); 
      queue_obj.push_into_queue(BITOR, 1); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 198 "includes/scanner/scanner.l"
{ // printf("%s\n", BITXOR);
      queue_obj.push_into_queue(BITXOR, 1); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 200 "includes/scanner/scanner.l"
{ // printf("%s\n", LPARA); 
      queue_obj.push_into_queue(LPARA, 1); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 202 "includes/scanner/scanner.l"
{ // printf("%s\n", RPARA);
      queue_obj.push_into_queue(RPARA, 1); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 204 "includes/scanner/scanner.l"
{ // printf("%s\n", LBRACKET);
      queue_obj.push_into_queue(LBRACKET, 1); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 206 "includes/scanner/scanner.l"
{ // printf("%s\n", RBRACKET); 
      queue_obj.push_into_queue(RBRACKET, 1); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 208 "includes/scanner/scanner.l"
{ // printf("%s\n", LCURLY);
      queue_obj.push_into_queue(LCURLY, 1); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 210 "includes/scanner/scanner.l"
{ // printf("%s\n", RCURLY);
      queue_obj.push_into_queue(RCURLY, 1); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 212 "includes/scanner/scanner.l"
{ // printf("%s\n", COMMA);
      queue_obj.push_into_queue(COMMA, 1); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "includes/scanner/scanner.l"
{ // printf("%s\n", SEMICOLON);
      queue_obj.push_into_queue(SEMICOLON, 1); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 216 "includes/scanner/scanner.l"
{ // printf("%s\n", ASSIGN);
      queue_obj.push_into_queue(ASSIGN, 1); }
	YY_BREAK
/* RULES FOR KEYWORDS */
/* ------------------ */
case 27:
YY_RULE_SETUP
#line 221 "includes/scanner/scanner.l"
{ // printf("%s\n", CHARSYM); 
	  queue_obj.push_into_queue(CHARSYM, 1);  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 223 "includes/scanner/scanner.l"
{ // printf("%s\n", INTSYM); 
	  queue_obj.push_into_queue(INTSYM, 1); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 225 "includes/scanner/scanner.l"
{ // printf("%s\n", VOIDSYM);
	  queue_obj.push_into_queue(VOIDSYM, 1); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 227 "includes/scanner/scanner.l"
{ // printf("%s\n", IFSYM);
	  queue_obj.push_into_queue(IFSYM, 1); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 229 "includes/scanner/scanner.l"
{ // printf("%s\n", ELSESYM);
	  queue_obj.push_into_queue(ELSESYM, 1); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 231 "includes/scanner/scanner.l"
{ // printf("%s\n", WHILESYM);
	  queue_obj.push_into_queue(WHILESYM, 1);  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "includes/scanner/scanner.l"
{ // printf("%s\n", FORSYM);
	  queue_obj.push_into_queue(FORSYM, 1); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 235 "includes/scanner/scanner.l"
{ // printf("%s\n", CONTINUESYM);
	  queue_obj.push_into_queue(CONTINUESYM, 1); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 237 "includes/scanner/scanner.l"
{ // printf("%s\n", BREAKSYM); 
	  queue_obj.push_into_queue(BREAKSYM, 1);  }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 239 "includes/scanner/scanner.l"
{ // printf("%s\n", RETURNSYM); 
	  queue_obj.push_into_queue(RETURNSYM, 1);  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 241 "includes/scanner/scanner.l"
{ // printf("%s\n", AUTOSYM); 
	  queue_obj.push_into_queue(AUTOSYM, 1); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 243 "includes/scanner/scanner.l"
{ // printf("%s\n", EXTERNSYM); 
	  queue_obj.push_into_queue(EXTERNSYM, 1);  }	
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 245 "includes/scanner/scanner.l"
{ // printf("%s\n", FLOATSYM); 
	  queue_obj.push_into_queue(FLOATSYM, 1);  }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 247 "includes/scanner/scanner.l"
{ // printf("%s\n", DOUBLESYM);
	  queue_obj.push_into_queue(DOUBLESYM, 1);  }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 249 "includes/scanner/scanner.l"
{ // printf("%s\n", SWITCHSYM);
	  queue_obj.push_into_queue(SWITCHSYM, 1);  }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 251 "includes/scanner/scanner.l"
{ // printf("%s\n", CASESYM); 
	  queue_obj.push_into_queue(CASESYM, 1); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 253 "includes/scanner/scanner.l"
{ // printf("%s\n", CONSTSYM);
	  queue_obj.push_into_queue(CONSTSYM, 1); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 255 "includes/scanner/scanner.l"
{ // printf("%s\n", DEFAULTSYM);
	  queue_obj.push_into_queue(DEFAULTSYM, 1); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 257 "includes/scanner/scanner.l"
{ // printf("%s\n", LONGSYM); 
	  queue_obj.push_into_queue(LONGSYM, 1); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 259 "includes/scanner/scanner.l"
{ // printf("%s\n", REGISTERSYM);
	  queue_obj.push_into_queue(REGISTERSYM, 1); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 261 "includes/scanner/scanner.l"
{ // printf("%s\n", SHORTSYM);
	  queue_obj.push_into_queue(SHORTSYM, 1); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 263 "includes/scanner/scanner.l"
{ // printf("%s\n", SIGNEDSYM);
	  queue_obj.push_into_queue(SIGNEDSYM, 1); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 265 "includes/scanner/scanner.l"
{ // printf("%s\n", STATICSYM); 
	  queue_obj.push_into_queue(STATICSYM, 1); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 267 "includes/scanner/scanner.l"
{ // printf("%s\n", UNSIGNEDSYM);
	  queue_obj.push_into_queue(UNSIGNEDSYM, 1); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 269 "includes/scanner/scanner.l"
{ // printf("%s\n", DOSYM); 
	  queue_obj.push_into_queue(DOSYM, 1);  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 271 "includes/scanner/scanner.l"
{ // printf("%s\n", ENUMSYM);
	  queue_obj.push_into_queue(ENUMSYM, 1); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 273 "includes/scanner/scanner.l"
{ // printf("%s\n", STRUCTSYM); 
	  queue_obj.push_into_queue(STRUCTSYM, 1); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 275 "includes/scanner/scanner.l"
{ // printf("%s\n", UNIONSYM); 
	  queue_obj.push_into_queue(UNIONSYM, 1); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 277 "includes/scanner/scanner.l"
{ // printf("%s\n", GOTOSYM);
	  queue_obj.push_into_queue(GOTOSYM, 1); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 279 "includes/scanner/scanner.l"
{ // printf("%s\n", SIZEOFSYM);
	  queue_obj.push_into_queue(SIZEOFSYM, 1); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 281 "includes/scanner/scanner.l"
{ // printf("%s\n", TYPEDEFSYM);
	  queue_obj.push_into_queue(TYPEDEFSYM, 1); }
	YY_BREAK
/* RULES FOR IDENTIFIIERS */
/* ---------------------- */
case 58:
YY_RULE_SETUP
#line 287 "includes/scanner/scanner.l"
{ queue_obj.push_into_queue(yytext,3); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 289 "includes/scanner/scanner.l"
{ queue_obj.push_into_queue(yytext,1); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 290 "includes/scanner/scanner.l"
{ // printf("%s\n", yytext); 
	  queue_obj.push_into_queue(yytext, 2); }
	YY_BREAK
/* RULES FOR LITERALS */
/* ------------------ */
case 61:
YY_RULE_SETUP
#line 295 "includes/scanner/scanner.l"
{ // printf("%s\n",yytext); 
	  queue_obj.push_into_queue(yytext, 1); }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 297 "includes/scanner/scanner.l"
{ // printf("%s\n",yytext);
	  queue_obj.push_into_queue(yytext, 1); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 300 "includes/scanner/scanner.l"
{ // printf("%c\n", DELIMITER);   
	    queue_obj.push_into_queue(yytext,1); }
	YY_BREAK
/* ignore any kind of comments; i.e. no 'action'! */
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 304 "includes/scanner/scanner.l"
{ // printf("%s\n", COMMENT) ;  
 			queue_obj.push_into_queue(yytext, 1); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 308 "includes/scanner/scanner.l"
ECHO;
	YY_BREAK
#line 1499 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 249 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 249 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 248);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 308 "includes/scanner/scanner.l"



/* ----- USER CODE PART ----- */
/* ========================== */
main(int argc, char **argv)
{
YY_BUFFER_STATE bp;
extern FILE* yyin;

if (argc>1) {
yyin = fopen(argv[2],"r");
} else {
yyin = stdin;
bp = yy_create_buffer(yyin,YY_BUF_SIZE); // YY_BUF_SIZE defined by flex, typically 16K=16384
yy_switch_to_buffer(bp); // tell it to use the buffer we just made
}
yylex();
queue_obj.generate_output_file(argv[1]);
}
